sudo: false
language: node_js
node_js:
- '0.12'
- 4
- 5
- 6
- 7
after_success: npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: kF1WSzVCG0nSPjwud32u2l43OAnSlu9uMQo6+jAxhc6OZW/QELwhv4zes0ibZTyzBx1yGwM7fVmqNxZCsnpftDvv4daX7MKeoe+kAnz/sVaWRRii2BTz0PhBIsiyRvZ9a2di/7etO6GvjPlR7grWg779CpOPxibQKWnLXSjFxSUFbHoq86zD4WkAaKz1AQWPfBROko9wo8NuhkGciFto4s3ItQmklCv4D/zlIh9h7aXBpZRrGA89JBOcWgANWLSdW9s0PRQ+iz+m1CDXPMsu7WcAqXKz9JaL3MskyN9LP0H5JHjg5X1scG4z8u8J4/pVHPIhsTn7yMxWkdC9lH0LIBzz0w9rbccW/zKg/9EGu9WKyHajJbEjbuxP2oKDCgslPM6G0BiN8Xh0b287xRQfkW0IbNPB7t/dQ+WsXWzU69+eopZYtcjiMW5QA0PmbM3x7WIZ0r2ZDtHWGSkQjL41DMd9AHu10pklQsEZ8x0QiBihFYoc0SW9MEZylunjgH5DOVW1G8z6VTBzYgAmP39ipMxqbrHE1KLpZvgwXaE2RrCQKZgneXf3Cdm9mUscpKlHNYgznUuLHQfgsOoC/tLACz3G1MR3J896kxOaXNhG7mB0+54O9nRBM8fRjUX+JotTAxXrrsuUQDAMX9En+2uJzVvTZw66aebJC1qAqQUt57c=
  on:
    tags: true
    repo: Brightspace/node-ecdsa-sig-formatter
    node: 5
