sudo: false
language: node_js
node_js:
  - '0.12'
  - 4
  - 6
  - 8
  - 10
after_success: npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 0655......8469
    secure: FawA6VEKDBIS4ow4f/vKzC+W8YlzQCgHA/CnAgEmtrkWBR73ADhuEk1Gl5YSYAbMccmKCsEEpmsQqgMC3ddALRIlifu6IzQE6+KQj9uXOwST9Y9f6+STznf0XHpTje2eBn5F9Wa92tzcSIQJbrLpuD5kq/32tiH0ZyhnmKuW4ZJwou/+wG4uuOnon6HBsqvy3u9nMCGnDPwdTkuAr7Hc5KWiMOVuayFoLpIZ5PKuIbne404iMmkIQVxeoDLgFRehqo5zxLP1YPbCic0Vdz9r++nz+7EaJbspGNK/K6K6tzR4bb+BfN9TVB8x97cf49vt+ZTnvhjqXnrkSii+PCTyyZ7O/0oMrLVMOzkJ1yjUoZDqFUtN4wJFl/kNKw+ICXWan8vFFpldAxsLsyvgTU5pLuL/20NJNMZK0AV9pfuNUPs3yDni7jH14xjIaYH5zzU/DDXOgy38sQNIDRvLlV2d6GFZpmC35bLopx8iH3SZ9u9LOVYRc4GjG8hLZY0Ca/nGcrGvvGjPPl6Xu4TjI0S/lmAv7XpqGsv/Lb2J0SjEZQwjhh/BpvIDPGGoPILqn13fhrg6bc/kfI1/hHG4fHCwKQsQVkfV8pK0d/ZcPbFL+McMz3b967adD+PIpJ5cHCsTkFzp3YmW62mIHKi1kwF6yC1q2GOvVzXlk8WaSkVyrrI=
  on:
    tags: true
    repo: Brightspace/node-ecdsa-sig-formatter
    node: 10
